export const REPORT_PAGES = [
  {
    id: "overview",
    shortLabel: "Overview",
    title: "Overview",
    subtitle: "Tổng quan dataset, chỉ số chính và thao tác đồng bộ.",
    kicker: "Silver Market Analytics",
    headline: "Silver Time Series Overview",
    description: "Trang tổng quan để đọc nhanh trạng thái dataset, các chỉ số chính và luồng thao tác đồng bộ dữ liệu.",
    panelLabel: "00 — Tổng quan",
    panelTitle: "Theo dõi giá bạc nhanh, gọn và dễ hiểu.",
    panelCopy: "Trang này tập trung vào các thông tin chính: khoảng dữ liệu hiện có, giá mới nhất và các thao tác lọc hoặc đồng bộ khi cần.",
  },
  {
    id: "trend",
    shortLabel: "Trend",
    title: "01 — Technical Analytics",
    subtitle: "Line chart, MA, return, candlestick, scatter, histogram và spread.",
    kicker: "Trend Reading",
    headline: "Silver Technical Analytics",
    description: "Tập trung vào chuỗi giá bạc cùng các biểu đồ kỹ thuật để đọc xu hướng, phân phối và tương quan.",
    panelLabel: "01 — Xu hướng giá",
    panelTitle: "Đọc nhanh xu hướng, tương quan và phân phối của giá bạc.",
    panelCopy: "Trang này gom bộ chart phân tích kỹ thuật cốt lõi để bạn nhìn được trend, spread và các tín hiệu tương quan trong cùng một flow.",
  },
  {
    id: "market",
    shortLabel: "Terminal",
    title: "02 — Market Terminal",
    subtitle: "Giao diện chart market riêng, ưu tiên cảm giác theo dõi giá.",
    kicker: "Market Terminal",
    headline: "Market Terminal",
    description: "Trang riêng cho chart kiểu terminal market, tập trung vào giá USD, sidebar quote và hiệu suất nhanh.",
    panelLabel: "02 — Market View",
    panelTitle: "Xem chart giá bạc theo kiểu market terminal.",
    panelCopy: "Trang này tách riêng phần nhìn chart để không trộn với forecast hay các bảng báo cáo khác.",
  },
  {
    id: "summary",
    shortLabel: "Stats",
    title: "03 — Summary Metrics",
    subtitle: "Toàn bộ thống kê backend trả về từ `/silver/summary`.",
    kicker: "Metric Summary",
    headline: "Summary Metrics",
    description: "Tổng hợp các thống kê mô tả quan trọng từ backend như mức giá, trung bình, biến động và drawdown.",
    panelLabel: "03 — Chỉ số tổng hợp",
    panelTitle: "Tập trung vào các chỉ số quan trọng nhất.",
    panelCopy: "Trang này gom các thống kê mô tả để bạn xem nhanh mức giá, trung bình, biến động và các mốc quan trọng của chuỗi.",
  },
  {
    id: "history",
    shortLabel: "Table",
    title: "04 — History Table",
    subtitle: "Preview dữ liệu thô đang lưu trong PostgreSQL.",
    kicker: "Dataset Browser",
    headline: "History Table",
    description: "Xem dữ liệu lịch sử theo từng page để duyệt bảng nhẹ hơn, tránh tải và render toàn bộ dataset cùng lúc.",
    panelLabel: "04 — Bảng dữ liệu",
    panelTitle: "Duyệt dữ liệu lịch sử theo từng trang.",
    panelCopy: "Trang này phù hợp khi cần xem dữ liệu gốc theo từng dòng, với phân trang để tải nhẹ hơn và dễ dò hơn.",
  },
  {
    id: "dataset_overview",
    shortLabel: "Dataset",
    title: "05 — Dataset Overview",
    subtitle: "Xem toàn bộ dataset với zoom/pan liên tục.",
    kicker: "Dataset Overview",
    headline: "Whole Dataset Overview",
    description: "Trang này tập trung vào toàn bộ chuỗi dữ liệu, có mini-map và thanh cuộn để zoom hoặc pan mượt hơn.",
    panelLabel: "05 — Toàn bộ dataset",
    panelTitle: "Xem toàn bộ dataset và zoom theo cửa sổ trượt.",
    panelCopy: "Không chia cứng theo 1D, 1M hay 1Y. Thay vào đó, bạn nhìn toàn bộ chuỗi rồi tự zoom và kéo vùng đang quan tâm.",
  },
  {
    id: "backtesting",
    shortLabel: "Backtesting",
    title: "06 — Model Backtesting",
    subtitle: "Kiểm tra hiệu suất từng mô hình ARX · MA · ARMA trên tập test.",
    kicker: "Backtesting Lab",
    headline: "Model Backtesting",
    description: "So sánh Actual vs Predicted trên tập kiểm tra, bảng xếp hạng MAE / RMSE / MAPE và hit rate hướng.",
    panelLabel: "06 — Kiểm thử mô hình",
    panelTitle: "Xem hiệu suất từng mô hình trên tập test.",
    panelCopy: "Hiển thị chart Actual vs Predicted cho từng mô hình, bảng so sánh MAE / RMSE / MAPE và direction accuracy.",
  },
  {
    id: "forecast",
    shortLabel: "Forecast",
    title: "07 — Model Forecast",
    subtitle: "Dự báo ngày kế tiếp bằng mô hình tốt nhất.",
    kicker: "Forecast Lab",
    headline: "Next-Day Forecast",
    description: "Dự báo ngày mai từ model đề xuất, consensus giá và khoảng tin cậy 95%.",
    panelLabel: "07 — Dự đoán",
    panelTitle: "Xem giá dự báo ngày mai từ mô hình tốt nhất.",
    panelCopy: "Ưu tiên model tốt nhất, giá dự báo ngày mai, delta so với giá hiện tại và CI 95%.",
  },
];

export const TABLE_PAGE_SIZE = 50;
export const MODEL_AR_ORDER = 5;
export const MODEL_MA_ORDER = 3;
export const MODEL_TEST_RATIO = 0.2;
